# Generated by Django 3.2 on 2020-11-23 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('senat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='senateur',
            name='slug',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
