# Generated by Django 3.2 on 2020-11-23 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('senat', '0002_senateur_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='senateur',
            name='slug',
            field=models.TextField(unique=True),
        ),
    ]
